kind = "mobile"
previewPath = "/"
title = "VOX AI"
version = "1.0.0"
id = "artifacts/vox-ai"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 23680

[services.development]
run = "pnpm --filter @workspace/vox-ai run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/vox-ai", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/vox-ai", "run", "serve" ]

[services.env]
PORT = "23680"
BASE_PATH = "/"
